"""form_update

Revision ID: 57cf7dc20411
Revises: f6711efc43ad
Create Date: 2024-06-05 03:53:35.049525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57cf7dc20411'
down_revision = 'f6711efc43ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('patient_email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.alter_column('doctor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_appointment_date')
        batch_op.drop_constraint('appointment_ibfk_2', type_='foreignkey')
        batch_op.drop_column('date')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', mysql.DATETIME(), nullable=True))
        batch_op.create_foreign_key('appointment_ibfk_2', 'patient', ['patient_id'], ['id'])
        batch_op.create_index('ix_appointment_date', ['date'], unique=False)
        batch_op.alter_column('doctor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('start_time')
        batch_op.drop_column('patient_email')
        batch_op.drop_column('patient_name')

    # ### end Alembic commands ###
