"""form_update

Revision ID: 8e5e9a69acec
Revises: e022803153ed
Create Date: 2024-06-05 04:38:07.562264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5e9a69acec'
down_revision = 'e022803153ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', existing_type=sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
