"""Add patient_id to appointment

Revision ID: c5dbf9a55d13
Revises: 2fa3f4c8e7a8
Create Date: 2024-06-07 01:18:03.263679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5dbf9a55d13'
down_revision = '2fa3f4c8e7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
