"""form_update

Revision ID: ce1097b7ddee
Revises: 57cf7dc20411
Create Date: 2024-06-05 04:06:32.519194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce1097b7ddee'
down_revision = '57cf7dc20411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('appointment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['patient_id'], ['id'])
        batch_op.drop_column('start_time')
        batch_op.drop_column('patient_name')
        batch_op.drop_column('patient_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('patient_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('start_time', mysql.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointment_ibfk_1', 'doctor', ['doctor_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
