"""form_update

Revision ID: e022803153ed
Revises: ce1097b7ddee
Create Date: 2024-06-05 04:27:36.467535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e022803153ed'
down_revision = 'ce1097b7ddee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
